plugins {
    id 'com.android.application'
}

android {
    namespace 'com.legendpolyfoams.lpplpms'
    compileSdk 35

    defaultConfig {
        applicationId "com.legendpolyfoams.lpplpms"
        minSdk 26
        targetSdk 35
        versionCode 9
        versionName "0.3.0"
    }

    signingConfigs {
        debug {
            storeFile file('lppl-pilot-debug.jks')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    buildTypes {
        debug {
            debuggable true
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}

dependencies {
}
